CREATE TABLE STUDENT_CLASS(
    ID_CLASS INT IDENTITY PRIMARY KEY,
    NAME_CLASS VARCHAR(100)
)

CREATE TABLE STUDENT(
    ID_STUDENT INT IDENTITY PRIMARY KEY,
    NAME_STUDENT VARCHAR(100),
    ID_CLASS INT
)